# Generated by Django 3.0.8 on 2020-08-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
